version: "3"
services:
  pythonic_portfolio:
    container_name: pythonic_portfolio
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - portfoliodb:/var/lib/mysql


  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot
    restart: always
    environment:
      - CERTBOT_EMAIL=juanescalada175@gmail.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - pythonic_portfolio

volumes:
  portfoliodb:
  nginx_secrets:
